spring:
  profiles:
    active: dev

---
server:
  port: 8201
spring:
  profiles: dev

eureka:
  client:

    service-url:
      defaultZone: http://localhost:8002/eureka/

---
server:
  port: 8202
spring:
  profiles: test

eureka:
  client:

    service-url:
      defaultZone: http://localhost:8002/eureka/,http://eureka2:8003/eureka/,http://eureka3:8004/eureka/